build:
  environment:
    php:
      version: 8.0

  tests:
    override:
      -
        command: SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1 ./vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml ./test
        coverage:
          file: build/logs/clover.xml
          format: clover

checks:
    php:
        code_rating: true
        duplication: true
